# Generated by Django 4.0.6 on 2022-08-03 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0004_alter_movie_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='currency',
            field=models.CharField(choices=[('D', 'Dollar'), ('E', 'Euro'), ('U', 'Uah')], default='U', max_length=1),
        ),
    ]
